export const IMAGES = {
  //icon

  cancel: require('./icons/cancel.png'),
  checked: require('./icons/checked.png'),
  hide: require('./icons/hide.png'),
  view: require('./icons/view.png'),
  google: require('./icons/google.png'),
  apple: require('./icons/apple.png'),
  otpImage: require('./icons/otpImage.png'),
  backArrow: require('./icons/backArrow.png'),
  create: require('./icons/create.png'),
  language: require('./icons/language.png'),
  profile: require('./icons/profile.png'),
  downArrow: require('./icons/downArrow.png'),
  home: require('./icons/home.png'),
  feed: require('./icons/feed.png'),
  feed2: require('./icons/feed2.png'),
  calendar: require('./icons/calendar.png'),
  new_profile: require('./icons/new_profile.png'),
  face: require('./icons/face.png'),
  bell: require('./icons/bell.png'),
  iBtn: require('./icons/iBtn.png'),
  rightArrow: require('./icons/rightArrow.png'),
  privacy: require('./icons/privacy.png'),
  file: require('./icons/file.png'),
  delete: require('./icons/delete.png'),
  logout: require('./icons/logout.png'),
  newlogout: require('./icons/newlogout.png'),
  search: require('./icons/search.png'),
  sort: require('./icons/sort.png'),
  close: require('./icons/close.png'),
  flag: require('./icons/flag.png'),
  phone: require('./icons/phone.png'),
  right: require('./icons/right.png'),
  backArrow2: require('./icons/backArrow2.png'),
  pdf: require('./icons/pdf.png'),
  star: require('./icons/star.png'),
  currency: require('./icons/currency.png'),
  marker: require('./icons/marker.png'),
  location: require('./icons/location.png'),
  home_marker: require('./icons/home_marker.png'),
  call: require('./icons/call.png'),
  message: require('./icons/message.png'),
  profile_avatar: require('./icons/profile_avatar.png'),
  dashed_rec: require('./icons/dashed_rec.png'),
  upload: require('./icons/upload.png'),
  ic_booking: require('./icons/ic_booking.png'),
  ic_completed: require('./icons/ic_completed.png'),
  ic_earning: require('./icons/ic_earning.png'),
  ic_request: require('./icons/ic_request.png'),
  user_profile_icon: require('./icons/user_profile_icon.png'),
  delete_account: require('./icons/Provider/delete_account.png'),
  pro_language: require('./icons/Provider/language.png'),
  lock: require('./icons/Provider/lock.png'),
  pro_logout: require('./icons/Provider/logout.png'),

  // Images
  // splashScreen: require("./Images/splashScreen.png"),
  Welcome_bg: require('./Images/Welcome_bg.png'),
  Welcome_bg1: require('./Images/Welcome_bg1.png'),
  Welcome_bg2: require('./Images/Welcome_bg2.png'),
  cleaning_basket: require('./Images/cleaning_basket.png'),
  buildings_services: require('./Images/buildings_services.png'),
  business_services: require('./Images/business_services.png'),
  car_services: require('./Images/car_services.png'),
  cleaning_sanitation: require('./Images/cleaning_sanitation.png'),
  construction_renovation: require('./Images/construction_renovation.png'),
  home_service: require('./Images/home_service.png'),
  lifestyle_events: require('./Images/lifestyle_events.png'),
  pet_services: require('./Images/pet_services.png'),
  repair_maintenance: require('./Images/repair_maintenance.png'),
  handyman_service: require('./Images/handyman_service.png'),
  dummy: require('./Images/dummy.png'),
  dummy_map: require('./Images/dummy_map.png'),
  dummy2: require('./Images/dummy2.png'),
  taprepair: require('./Images/tap_repair.png'),
  acrepair: require('./Images/ac_repair.png'),
  carrepair: require('./Images/car_repair.png'),
  petService: require('./Images/petService.png'),
  user_profile: require('./Images/user_profile.png'),
  battery: require('./Images/battery.png'),
};

export const Animation = {};
